// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvrxrgshvgbyujwrkmpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2cnhyZ3NodmdieXVqd3JrbXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjk5MzUsImV4cCI6MjA2NDg0NTkzNX0.y0Mjb0lkv7Ve_BfGOVcEE3A6IBqXh4i1g1NB9W_byks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);